# Generated by Django 3.2.7 on 2021-09-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('passWord', models.CharField(max_length=100)),
                ('accessToken', models.CharField(max_length=100)),
            ],
        ),
    ]
